### ISSUE TITLE
Can not work with jQuery 3+

### ISSUE THREAD

**Issue by jqueryscript** [thdoan/unobscure-text#1]
Seems like cannot work with jQuery 3.2.1+.

**Comment by thdoan** [comment]
Hi, thanks for reporting this. Unfortunately, this plugin cannot support jQuery 3 because it needs to support IE 9. You are free to fork it and make it work with jQuery 3 if you don't need the IE 9 support.

**Comment by thdoan** [comment]
I recommend you use the [jq-clipthru plugin](https://github.com/salsita/jq-clipthru) instead, which is more flexible than my plugin.

Demo: https://codepen.io/thdoan/pen/GEoZzg
